### ISSUE TITLE
makeAugmentedSchema({ typeDefs }) TypeError: Cannot set property 'Query' of undefined since v1.0.3

### ISSUE THREAD

**Issue by itaylorweb** [neo4j-graphql/neo4j-graphql-js#126]
Since updating to v1.0.3.  When calling makeAugmentedSchema:

```javascript
const schema = makeAugmentedSchema({ typeDefs });
```
I get the error: 
```
/apollo-server/node_modules/neo4j-graphql-js/dist/augment.js:84
    resolvers.Query = queryResolvers;
                    ^

TypeError: Cannot set property 'Query' of undefined
    at augmentResolvers (/apollo-server/node_modules/neo4j-graphql-js/dist/augment.js:84:21)
    at makeAugmentedExecutableSchema (/apollo-server/node_modules/neo4j-graphql-js/dist/augmentSchema.js:48:58)
    at makeAugmentedSchema (/apollo-server/node_modules/neo4j-graphql-js/dist/index.js:548:59)
    at Object.<anonymous> (/apollo-server/apollo-server.js:9:16)
    at Module._compile (module.js:652:30)
    at Module._compile (/apollo-server/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (/apollo-server/node_modules/pirates/lib/index.js:88:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

it works fine if I add resolvers as an empty object to makeAugmentedSchema:
```javascript
const schema = makeAugmentedSchema({ typeDefs, resolvers: {} });
```

**Comment by johnymontana** [comment]
Hey @itaylorweb this should be fixed in v1.0.4 (just released). Thanks for reporting!
