### ISSUE TITLE
Implementing Custom Scalars

### ISSUE THREAD

**Issue by lichri11** [neo4j-graphql/neo4j-graphql-js#233]
First and foremost, amazing library!

I'm trying to define a custom JSON scalar, but I'm running in errors at the schema augmentation part.

`Error: Unknown type "JSON".
    at assertValidSDL (/Users/chris/projects/bxserver/node_modules/graphql/validation/validate.js:89:11)
    at Object.buildASTSchema (/Users/chris/projects/bxserver/node_modules/graphql/utilities/buildASTSchema.js:78:34)
    at Object.buildSchemaFromTypeDefinitions (/Users/chris/projects/bxserver/node_modules/graphql-tools/src/generate/buildSchemaFromTypeDefinitions.ts:43:32)
    at makeExecutableSchema (/Users/chris/projects/bxserver/node_modules/graphql-tools/src/makeExecutableSchema.ts:52:16)
    at augmentedSchema (/Users/chris/projects/bxserver/node_modules/neo4j-graphql-js/dist/augment.js:52:49)
    at Object.augmentSchema (/Users/chris/projects/bxserver/node_modules/neo4j-graphql-js/dist/index.js:191:39)
    at Object.<anonymous> (/Users/chris/projects/bxserver/src/index.ts:51:19)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Module.m._compile (/Users/chris/projects/bxserver/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:745:10)`

Any suggestions on how to make this work would be greatly appreciated!

Thanks.

**Comment by lichri11** [comment]
Never mind, I just have to write custom @cyphers on the fields where its used and no problems.

**Comment by ASeaOtter** [comment]
I'm have the same problem with a custom scalar date. How did you have to customize the **@cyphers** on the fields where its used?
