### ISSUE TITLE
TypeError: Cannot set property 'isAuthenticated' of undefined

### ISSUE THREAD

**Issue by igokul1973** [neo4j-graphql/neo4j-graphql-js#313]
Hello and thank you for the great library!

However... When trying to implement authentication, using https://grandstack.io/docs/neo4j-graphql-js-middleware-authorization.html, as soon as I add:
``
...
const augmentedSchema = augmentSchema(schema, {
    query: {
        exclude: ['Book']
    },
    mutation: {
        exclude: ['Book']
    },
    auth: {
        isAuthenticated: true
    }
});
...
``
I get the following error:
``
/Users/igor/Sites/docker/bron/apollo.bron.l/node_modules/neo4j-graphql-js/dist/auth.js:71
    schemaDirectives['isAuthenticated'] = _graphqlAuthDirectives.IsAuthenticatedDirective;
                                        ^
TypeError: Cannot set property 'isAuthenticated' of undefined
    at possiblyAddDirectiveImplementations (/Users/igor/Sites/docker/bron/apollo.bron.l/node_modules/neo4j-graphql-js/dist/auth.js:71:41)
    at augmentedSchema (/Users/igor/Sites/docker/bron/apollo.bron.l/node_modules/neo4j-graphql-js/dist/augment.js:52:72)
    at augmentSchema (/Users/igor/Sites/docker/bron/apollo.bron.l/node_modules/neo4j-graphql-js/dist/index.js:193:39)
    at Object.<anonymous> (/Users/igor/Sites/docker/bron/apollo.bron.l/src/augmentedSchema.ts:14:25)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Module.m._compile (/Users/igor/Sites/docker/bron/apollo.bron.l/node_modules/ts-node/src/index.ts:473:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/igor/Sites/docker/bron/apollo.bron.l/node_modules/ts-node/src/index.ts:476:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[nodemon] app crashed - waiting for file changes before starting...
``
I've made a debug attempt, looked at the source code, and can see the lines (43-47) in auth.js that make no sense to me, because the argument `schemaDirectives` is nowhere to be found in the file above those lines of code:
``
const schemaDirectives = possiblyAddDirectiveImplementations(
    schemaDirectives,
    typeMap,
    config
  );
``
Would you please look into the problem?
--------------------------------------------------------------------------------------------
Also, according to the documentation:
![image](https://user-images.githubusercontent.com/5454915/65360515-e452ee00-dc08-11e9-8fd2-08c6f0741858.png)
My question is - is it a bash command, or you mean exporting from the JS module??? Please clarify...

**Comment by michaeldgraham** [comment]
https://github.com/neo4j-graphql/neo4j-graphql-js/issues/608
