### ISSUE TITLE
Excluding types does not exclude their filters

### ISSUE THREAD

**Issue by slowercz** [neo4j-graphql/neo4j-graphql-js#317]
Creating schema with excluded types lead to  an error:

```Error: Unknown type "_VisPathEdgesFilter". Did you mean "_VisPathEdges" or "_VisPathEdgesDirections"?

Unknown type "_VisPathEdgesFilter". Did you mean "_VisPathEdges" or "_VisPathEdgesDirections"?
    at assertValidSDL (/Users/trnka/GraphAware/pathToProject/node_modules/graphql/validation/validate.js:108:11)
    at Object.buildASTSchema (/Users/trnka/GraphAware/pathToProject/node_modules/graphql/utilities/buildASTSchema.js:71:34)
    at Object.buildSchemaFromTypeDefinitions (/Users/trnka/GraphAware/pathToProject/node_modules/graphql-tools/dist/generate/buildSchemaFromTypeDefinitions.js:23:28)
    at makeExecutableSchema (/Users/trnka/GraphAware/pathToProject/node_modules/graphql-tools/dist/makeExecutableSchema.js:26:29)
    at makeAugmentedExecutableSchema (/Users/trnka/GraphAware/pathToProject/node_modules/neo4j-graphql-js/dist/augment.js:81:49)
    at makeAugmentedSchema (/Users/trnka/GraphAware/pathToProject/node_modules/neo4j-graphql-js/dist/index.js:229:53)
    at Module../src/index.ts (/Users/trnka/GraphAware/pathToProject/build/index.js:347:92)
    at __webpack_require__ (/Users/trnka/GraphAware/pathToProject/build/index.js:20:30)
    at /Users/trnka/GraphAware/pathToProject/build/index.js:84:18
    at Object.<anonymous> (/Users/trnka/GraphAware/pathToProject/build/index.js:87:10)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
    at internal/main/run_main_module.js:17:11
```

Creating the schema:
```makeAugmentedSchema({
  typeDefs: loadSchema('someMyFile'),
  resolvers,
  config: {
    auth: {
    },
    query: {
      exclude: [

        'VisNode',
        'VisEdge',
        'VisPath',
      ],
    },
    mutation: {
      exclude: [
        'VisNode',
        'VisEdge',
        'VisPath',
        'MapEntry',
      ],
    },
  },
});```

graphQL schema:
```
type VisNode {
  type: String!
}

type VisEdge {
  name: String!
  from: VisNode!
  to: VisNode!
}

type VisPath {
  nodes: [VisNode!]!
  edges: [VisEdge!]!
}
```

**Comment by slowercz** [comment]
Edit - added that the problem seems to be in the `from` and `to` frield on the VisEdge

**Comment by AshkanHovold** [comment]
Thank you!

**Comment by michaeldgraham** [comment]
https://github.com/neo4j-graphql/neo4j-graphql-js/issues/608
