### ISSUE TITLE
@cypher returns List, not Node

### ISSUE THREAD

**Issue by xizall** [neo4j-graphql/neo4j-graphql-js#354]
I have computed property, but the cypher query returns list with one node instead of single node.
Example
```
type CablePlug {
  type: String!
  cable: Cable! @cypher(
    statement: """
      MATCH (this)-[:IS_PLUG_A_OF_CABLE|:IS_PLUG_B_OF_CABLE]->(cable :Cable)
      RETURN cable
    """
  )
}

type Cable {
  type: String!
  plugA: CablePlug! @relation(name: "IS_PLUG_A_OF_CABLE", direction: "IN")
  plugB: CablePlug! @relation(name: "IS_PLUG_B_OF_CABLE", direction: "IN")
}
```
Query
```
query {
  CablePlug {
    cable { type }
  }
}
```
Generated cypher
```
MATCH (`cablePlug`:`CablePlug`)
RETURN `cablePlug` {
  cable: [
    cablePlug_cable IN apoc.cypher.runFirstColumn(
      "MATCH (this)-[:IS_PLUG_A_OF_CABLE|:IS_PLUG_B_OF_CABLE]->(cable :Cable)
      RETURN cable", 
      {this: cablePlug},
      true
    ) | cablePlug_cable { .type }
  ]
} AS `cablePlug`
```
Response
```
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Cable.type.",
      "locations": [
        {
          "line": 4,
          "column": 7
        }
      ],
      "path": [
        "CablePlug",
        0,
        "cable",
        "type"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
        "stacktrace": [
          "Error: Cannot return null for non-nullable field Cable.type.",
          "    at completeValue (/backend/node_modules/graphql/execution/execute.js:560:13)",
          "    at completeValueCatchingError (/backend/node_modules/graphql/execution/execute.js:495:19)",
          "    at resolveField (/backend/node_modules/graphql/execution/execute.js:435:10)",
          "    at executeFields (/backend/node_modules/graphql/execution/execute.js:275:18)",
          "    at collectAndExecuteSubfields (/backend/node_modules/graphql/execution/execute.js:713:10)",
          "    at completeObjectValue (/backend/node_modules/graphql/execution/execute.js:703:10)",
          "    at completeValue (/backend/node_modules/graphql/execution/execute.js:591:12)",
          "    at completeValue (/backend/node_modules/graphql/execution/execute.js:557:21)",
          "    at completeValueCatchingError (/backend/node_modules/graphql/execution/execute.js:495:19)",
          "    at resolveField (/backend/node_modules/graphql/execution/execute.js:435:10)"
        ]
      }
    }
  ],
  "data": {
    "CablePlug": [
      null
    ]
  }
}
```
For some reason generated cypher has array brackets `[]` around cable property although it is stated as single Node and not as List of Nodes.

**Comment by imkleats** [comment]
The `customCypherField` function in `translate.js` checks for whether a field is a list, and if it is not is supposed to insert `head()` into the generated query, so I don't know why it's not showing up in what you provided. However, the error you're getting isn't what I'd expect from the GraphQL execution receiving a list when it was expecting an item.

The error you're getting seems to suggest that you're not pulling in any matches for Cable (i.e. "Cannot return null for non-nullable type Cable.type".  I have a hunch why in that the cypher documentation suggests a syntax of `(a)-[r:TYPE1|TYPE2]->(b)`.  Would you mind taking out the second colon from the relationship in your custom cypher query so it reads `[:IS_PLUG_A_OF_CABLE|IS_PLUG_B_OF_CABLE]` and seeing if you get different results?

**Comment by michaeldgraham** [comment]
https://github.com/neo4j-graphql/neo4j-graphql-js/issues/608
