### ISSUE TITLE
"TypeError: Cannot read property 'isInt' of undefined" in v2.12.1

### ISSUE THREAD

**Issue by digicjm** [neo4j-graphql/neo4j-graphql-js#391]
Started getting the following error after updating to 2.12.1:

query:
```
query RoomUtilization {
  Activity {
    resources {
      assignments {
        name
      }
    }
  }
}
```

stacktrace:
```
"stacktrace": [
            "TypeError: Cannot read property 'isInt' of undefined",
            "    at D:\\home\\site\\wwwroot\\node_modules\\neo4j-graphql-js\\dist\\utils.js:172:25",
            "    at baseClone (D:\\home\\site\\wwwroot\\node_modules\\lodash\\lodash.js:2627:67)",
            "    at Function.cloneDeepWith (D:\\home\\site\\wwwroot\\node_modules\\lodash\\lodash.js:11121:14)",
            "    at extractQueryResult (D:\\home\\site\\wwwroot\\node_modules\\neo4j-graphql-js\\dist\\utils.js:171:31)",
            "    at _callee$ (D:\\home\\site\\wwwroot\\node_modules\\neo4j-graphql-js\\dist\\index.js:119:76)",
            "    at tryCatch (D:\\home\\site\\wwwroot\\node_modules\\regenerator-runtime\\runtime.js:45:40)",
            "    at Generator.invoke [as _invoke] (D:\\home\\site\\wwwroot\\node_modules\\regenerator-runtime\\runtime.js:271:22)",
            "    at Generator.prototype.(anonymous function) [as next] (D:\\home\\site\\wwwroot\\node_modules\\regenerator-runtime\\runtime.js:97:21)",
            "    at asyncGeneratorStep (D:\\home\\site\\wwwroot\\node_modules\\@babel\\runtime-corejs2\\helpers\\asyncToGenerator.js:5:24)",
            "    at _next (D:\\home\\site\\wwwroot\\node_modules\\@babel\\runtime-corejs2\\helpers\\asyncToGenerator.js:27:9)"
          ]
        }
```

**Comment by johnymontana** [comment]
This should have been fixed in a previous release. Please reopen the issue if you're still seeing issues.
