### ISSUE TITLE
CustomCameras mutation returns an error..

### ISSUE THREAD

**Issue by dmitryyankowski** [neo4j-graphql/neo4j-graphql-js#405]
Trying to run the following mutation from the example:
```
mutation CustomCamerasMutation {
  CustomCameras {
    id
  }
}
```

The actual mutation in the schema looks like the following:
```
CustomCameras: [Camera]
    @cypher(
      statement: """
      CREATE (newCamera:Camera:NewCamera {id: apoc.create.uuid(), type: 'macro', features: ['selfie', 'zoom']})
      CREATE (oldCamera:Camera:OldCamera {id: apoc.create.uuid(), type: 'floating', smell: 'rusty' })
      RETURN [newCamera, oldCamera]
      """
    )
```

However.. it returns the following error:
```
{
  "errors": [
    {
      "message": "List{(138), (139)} (of class org.neo4j.values.virtual.ListValue$JavaListListValue)",
      "locations": [
        {
          "line": 8,
          "column": 3
        }
      ],
      "path": [
        "CustomCameras"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "code": "Neo.DatabaseError.Statement.ExecutionFailed",
          "name": "Neo4jError",
          "stacktrace": [
            "Neo4jError: List{(138), (139)} (of class org.neo4j.values.virtual.ListValue$JavaListListValue)",
            ": ",
            "    at captureStacktrace (C:\\Users\\Dmitry\\Documents\\apollo\\node_modules\\neo4j-driver\\lib\\result.js:263:15)",
            "    at new Result (C:\\Users\\Dmitry\\Documents\\apollo\\node_modules\\neo4j-driver\\lib\\result.js:68:19)",
            "    at newCompletedResult (C:\\Users\\Dmitry\\Documents\\apollo\\node_modules\\neo4j-driver\\lib\\transaction.js:449:10)",
            "    at Object.run (C:\\Users\\Dmitry\\Documents\\apollo\\node_modules\\neo4j-driver\\lib\\transaction.js:287:14)",
            "    at Transaction.run (C:\\Users\\Dmitry\\Documents\\apollo\\node_modules\\neo4j-driver\\lib\\transaction.js:123:32)",
            "    at C:\\Users\\Dmitry\\Documents\\apollo\\packages\\api\\node_modules\\neo4j-graphql-js\\dist\\index.js:123:25",
            "    at TransactionExecutor._safeExecuteTransactionWork (C:\\Users\\Dmitry\\Documents\\apollo\\node_modules\\neo4j-driver\\lib\\internal\\transaction-executor.js:134:22)",
            "    at TransactionExecutor._executeTransactionInsidePromise (C:\\Users\\Dmitry\\Documents\\apollo\\node_modules\\neo4j-driver\\lib\\internal\\transaction-executor.js:122:32)",
            "    at C:\\Users\\Dmitry\\Documents\\apollo\\node_modules\\neo4j-driver\\lib\\internal\\transaction-executor.js:61:15",
            "    at new Promise (<anonymous>)"
          ]
        }
      }
    }
  ],
  "data": {
    "CustomCameras": null
  }
}
```

**Any ideas what i'm doing wrong?**

**Comment by dmitryyankowski** [comment]
Anyone?

**Comment by dmitryyankowski** [comment]
@michaeldgraham mind taking a look at this issue too please? :)
