### ISSUE TITLE
Filter does not work on @relation Types

### ISSUE THREAD

**Issue by pmualaba** [neo4j-graphql/neo4j-graphql-js#423]
**Schema:** 

`type Product {
  id: ID!
  name: String
  description: String
  isRepresentedAs: [ProductPageRelation]
}

type Page {
  id: ID!
  name: String
  description: String
  isRepresentationOf: [ProductPageRelation]
}

type ProductPageRelation @relation(name: "IS_REPRESENTED_AS") {
  from: Product
  to: Page
  rating: Float
  isMany: Boolean
  timestamp: Int
}`

**Query:**

`query {
    Product(filter: {name_contains: "iPhone"}) {
        id
        name
        isRepresentedAs (filter: {name_contains: "iPhone page"}) {
          rating
          isMany
          timestamp
          Page {
            id
            name
            description
            isRepresentationOf {
              Product  {
                id
                name
              }
            }
          }
        }
    }
}`

**Returned Error:**

`{
    "errors": [
        {
            "message": "Field \"name_contains\" is not defined by type _ProductProductPageRelationFilter.",
            "locations": [
                {
                    "line": 5,
                    "column": 35
                }
            ],
            "extensions": {
                "code": "GRAPHQL_VALIDATION_FAILED",
                "exception": {
                    "stacktrace": [
                        "GraphQLError: Field \"name_contains\" is not defined by type _ProductProductPageRelationFilter.",
                        "    at ObjectField (/home/pmualaba/Development/bio8/biokube/node_modules/graphql/validation/rules/ValuesOfCorrectType.js:103:29)",
                        "    at Object.enter (/home/pmualaba/Development/bio8/biokube/node_modules/graphql/language/visitor.js:324:29)",
                        "    at Object.enter (/home/pmualaba/Development/bio8/biokube/node_modules/graphql/language/visitor.js:375:25)",
                        "    at visit (/home/pmualaba/Development/bio8/biokube/node_modules/graphql/language/visitor.js:242:26)",
                        "    at Object.validate (/home/pmualaba/Development/bio8/biokube/node_modules/graphql/validation/validate.js:73:24)",
                        "    at validate (/home/pmualaba/Development/bio8/biokube/node_modules/apollo-server-core/src/requestPipeline.ts:444:14)",
                        "    at Object.<anonymous> (/home/pmualaba/Development/bio8/biokube/node_modules/apollo-server-core/src/requestPipeline.ts:260:32)",
                        "    at Generator.next (<anonymous>)",
                        "    at fulfilled (/home/pmualaba/Development/bio8/biokube/node_modules/apollo-server-core/dist/requestPipeline.js:5:58)",
                        "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
                    ]
                }
            }
        }
    ]
}`

**Comment by johnymontana** [comment]
I think in this case you want to move the filter argument higher up into the selection set. Something like this:

```
query {
    Product(filter: {name_contains: "iPhone"}) {
        id
        name
        isRepresentedAs(filter: {Page: {name_contains: "iPhone page"}} )  {
          rating
          isMany
          timestamp
          Page {
            id
            name
            description
            isRepresentationOf {
              Product  {
                id
                name
              }
            }
          }
        }
    }
}
```

**Comment by pmualaba** [comment]
I tried that also but it gave the same type of error. Only when using the "simple" relation syntax (without relation properties) it works as specified in the docs.

**Comment by Phylodome** [comment]
I'm also seeing this problem. Just had a nested filter cease to work when switching from the inline `@relation` syntax type to a dedicated `@relation`-annotated type containing properties.

**Comment by michaeldgraham** [comment]
https://github.com/neo4j-graphql/neo4j-graphql-js/issues/608
