### ISSUE TITLE
Federate neo4j datasource with anything else.

### ISSUE THREAD

**Issue by agnewp** [neo4j-graphql/neo4j-graphql-js#435]
In the apollo federation guide [here](https://grandstack.io/docs/apollo-federation-gateway-with-neo4j.html#resolving-entity-extension-fields) the note in the documentation claims:

> An implementing service uses reference resolvers for providing data for the fields it resolves for its extensions of entities defined by other services. These reference resolvers are generated during schema augmentation.

the problem comes when i am attempting to extend an entity that is NOT in a neo4j database. how can my entity resolvers be auto generated since neo4j can't know how to resolve these kind of entity's fields?

'simple' example:
Movie schema + server
```
import { ApolloServer, gql } from "apollo-server-express";
import { buildFederatedSchema } from "@apollo/federation";

const typeDefs = gql`
  type Movie @key(fields: "title") {
    id: ID!
    title: String!
    year: Int
    imdbRating: Float
  }

  type Query {
    getMyMovies: [Movie]
  }
`;

const lameMovieDatabase = [
  { title: "Jurassic Park" },
  {
    title: "Unforgiven",
    year: 1234,
    imdbRating: 2.3,
  },
  { title: "derp3" },
  { title: "derp4" },
  {  title: "derp5" },
  { title: "derp6" },
];

const resolvers = {
  Query: {
    async getMyMovies(thing) {
      return lameMovieDatabase;
    },
  },
  Movie: {
    __resolveReference(Movie, { datasources }) {
      return datasources.movies.getMoveByTitle(Movie.title);
    },
  },
};

class MoviesDS {
  getMoveByTitle(title) {
    return lameMovieDatabase.find((movie) => movie.title == title);
  }
}

// register this as express middleware under the specified path for the supplied expres router
export const MovieMiddleware = (path, cb) => {
  const srv = new ApolloServer({
    schema: buildFederatedSchema([{ typeDefs, resolvers }]),
    datasources: () => {
      movies: new MoviesDS();
    },
  });
  cb(srv.getMiddleware({ path: path }));
};
```

neo4j movie genre 
```
import { ApolloServer, gql } from "apollo-server-express";
import { buildFederatedSchema } from "@apollo/federation";
import { makeAugmentedSchema } from "neo4j-graphql-js";
import neo4j from "neo4j-driver";

const typeDefs = gql`
  extend type Movie @key(fields: "title") {
    title: String! @external @requires(fields: "title")
    genres: [Genre] @relation(name: "IN_GENRE", direction: "OUT")
  }
  type Genre {
    name: String
    movies: [Movie] @relation(name: "IN_GENRE", direction: "IN")
  }
`;

export const getNeoMiddleware = (path, cb) => {
  const driver = neo4j.driver(
    "bolt://localhost:11003",
    neo4j.auth.basic("map", "password123")
  );
  const schema = buildFederatedSchema([
    makeAugmentedSchema({
      typeDefs: typeDefs,
      //resolvers: resolvers,
      config: { isFederated: true },
    }),
  ]);
  const srv = new ApolloServer({
    schema: schema,
    //schemaDirectives: [{ cypher: cypherDirective, relation: relationDirective }],
    context: () => {
      return { driver };
    },
  });
  cb(srv.getMiddleware({ path: path }));
};
```

federated server
```
import { ApolloGateway } from "@apollo/gateway";
import { ApolloServer } from "apollo-server-express";
import express from "express";
import pino from "pino";
import { getNeoMiddleware } from "./neo";
import { MovieMiddleware } from "./movie";

const gw = new ApolloGateway({
  serviceList: [
    {
      name: "neo",
      url: "dfdf",
    },
  ],
});

const logger = pino({
  name: "app-name",
  level: "debug",
});

const port = process.env.PORT || 3000;

const NEO_PATH = "/neo";
const MOVIE_PATH = "/movie";
const GATEWAY_PATH = "/gql";

// execute async function right away
(async () => {
  const app = express();

  const gateway = new ApolloGateway({
    serviceList: [
      { name: "neo", url: `http://localhost:${port}${NEO_PATH}` },
      { name: "movie", url: `http://localhost:${port}${MOVIE_PATH}` },
    ],
    debug: true,
  });

  getNeoMiddleware(`${NEO_PATH}`, (middleware) => {
    app.use(middleware);
  });

  MovieMiddleware(`${MOVIE_PATH}`, (middleware) => {
    app.use(middleware);
  });

  const gwserver = new ApolloServer({
    gateway: gateway,
    logger: logger,
    tracing: false,
    cacheControl: false,
    subscriptions: false,
    introspection: true,
    playground: true,
  });

  app.use(gwserver.getMiddleware({ path: GATEWAY_PATH }));

  await new Promise((resolve) => {
    const srv = app.listen(port);
    srv.on("listening", () => {
      logger.info("GQL server running on %s", port);
      resolve();
    });
  });
})();
```

now a query like this will work fine where i am getting my Movies with the federated genres
```
query a {
  getMyMovies {
    title
    year
    imdbRating
    genres {
      name
    }
  }
}
```

but a query like this will give errors where i am getting my genre with the federated Movies
```
query c {
  Genre (name: "scary"){
    name
     movies{
      title
      year
      imdbRating
    }
  }
}
```
errors:
```
{
  "errors": [
    {
      "message": "Cannot read property 'movies' of undefined",
      "path": [
        "_entities"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "serviceName": "movie",
        "query": "query($representations:[_Any!]!){_entities(representations:$representations){...on Movie{year imdbRating}}}",
        "variables": {
          "representations": [
            {
              "__typename": "Movie",
              "title": "Unforgiven"
            }
          ]
        },
        "exception": {
          "stacktrace": [
            "TypeError: Cannot read property 'movies' of undefined",
            "    at __resolveReference (/Users/derpmcderpface/Documents/federated-neo4j/src/movie.js:38:26)",
            "    at /Users/derpmcderpface/Documents/federated-neo4j/node_modules/@apollo/federation/src/types.ts:97:22",
            "    at Array.map (<anonymous>)",
            "    at resolve (/Users/derpmcderpface/Documents/federated-neo4j/node_modules/@apollo/federation/src/types.ts:80:28)",
            "    at field.resolve (/Users/derpmcderpface/Documents/federated-neo4j/node_modules/graphql-extensions/src/index.ts:274:18)",
            "    at resolveFieldValueOrError (/Users/derpmcderpface/Documents/federated-neo4j/node_modules/graphql/execution/execute.js:467:18)",
            "    at resolveField (/Users/derpmcderpface/Documents/federated-neo4j/node_modules/graphql/execution/execute.js:434:16)",
            "    at executeFields (/Users/derpmcderpface/Documents/federated-neo4j/node_modules/graphql/execution/execute.js:275:18)",
            "    at executeOperation (/Users/derpmcderpface/Documents/federated-neo4j/node_modules/graphql/execution/execute.js:219:122)",
            "    at executeImpl (/Users/derpmcderpface/Documents/federated-neo4j/node_modules/graphql/execution/execute.js:104:14)"
          ]
        }
      }
    }
  ],
  "data": {
    "Genre": [
      {
        "name": "scary",
        "movies": [
          {
            "title": "Unforgiven",
            "year": null,
            "imdbRating": null
          }
        ]
      }
    ]
  }
}
```

**Comment by agnewp** [comment]
wellllll, i big nevermind on this. I messed up on the 'dataSources' in the Movies server.
should be: 
```
import { ApolloServer, gql } from "apollo-server-express";
import { buildFederatedSchema } from "@apollo/federation";
import { RESTDataSource } from "apollo-datasource-rest";

import pino from "pino";

const logger = pino({
  name: "movie",
  level: "debug",
});

const typeDefs = gql`
  type Movie @key(fields: "title") {
    id: ID!
    title: String!
    year: Int
    imdbRating: Float
  }

  type Query {
    getMyMovies: [Movie]
  }
`;

const lameMovieDatabase = [
  { title: "Jurassic Park" },
  {
    title: "Unforgiven",
    year: 1234,
    imdbRating: 2.3,
  },
  { title: "derp3" },
  { title: "derp4" },
  { title: "derp5" },
  { title: "derp6" },
];

const resolvers = {
  Query: {
    async getMyMovies(thing) {
      return lameMovieDatabase;
    },
  },
  Movie: {
    __resolveReference(Movie, { dataSources }) {
      let obj = dataSources.movies.getMoveByTitle(Movie.title);
      logger.debug("Movie __resolveReference called %d", obj.year);
      return obj;
    },
  },
};

class MoviesDS extends RESTDataSource {
  constructor() {
    super();
  }
  async getMoveByTitle(title) {
    return lameMovieDatabase.find((movie) => movie.title == title);
  }
}

// register this as express middleware under the specified path for the supplied expres router
export const MovieMiddleware = (path, cb) => {
  const moviesDS = new MoviesDS();
  const srv = new ApolloServer({
    schema: buildFederatedSchema([{ typeDefs, resolvers }]),
    dataSources: () => {
      return {
        movies: moviesDS,
      };
    },
  });
  cb(srv.getMiddleware({ path: path }));
};

```
