### ISSUE TITLE
how to get relation/cypher directives accepted by codegen?

### ISSUE THREAD

**Issue by AdrienLemaire** [neo4j-graphql/neo4j-graphql-js#442]
Looking at #290, it seems like `apollo client:codegen` should work with grandstack , but I'm getting the following error whenever I try to generate my types:

```console
$ npm run codegen

> project-client@2.0.1 codegen /home/dori/Projects/Work/project-v2/platform_v2/client
> apollo client:codegen --target typescript --watch

CLIError: Error in "Loading schema for project": GraphQLSchemaValidationError: Unknown directive "relation".

Unknown directive "cypher".

Unknown directive "cypher".
    at Object.error (/home/dori/Projects/Work/project-v2/platform_v2/client/node_modules/@oclif/errors/lib/index.js:22:17)
    at Generate.error (/home/dori/Projects/Work/project-v2/platform_v2/client/node_modules/@oclif/command/lib/command.js:60:23)
    at OclifLoadingHandler.showError (/home/dori/Projects/Work/project-v2/platform_v2/client/node_modules/apollo/lib/OclifLoadingHandler.js:28:22)
    at OclifLoadingHandler.handle (/home/dori/Projects/Work/project-v2/platform_v2/client/node_modules/apollo/lib/OclifLoadingHandler.js:13:18)
    at async GraphQLClientProject.loadServiceSchema (/home/dori/Projects/Work/project-v2/platform_v2/client/node_modules/apollo-language-server/lib/project/client.js:94:9)
    at async Promise.all (index 1) {
  oclif: { exit: 2 },
  code: undefined
}
  ✖ Loading Apollo Project
    → Unknown directive "cypher".
    Generating query files
Press any key to stop.
[GraphQL error]: 406: Not Acceptable
Error: 406: Not Acceptable
    at ApolloEngineClient.loadSchemaTagsAndFieldStats (/home/dori/Projects/Work/project-v2/platform_v2/client/node_modules/apollo-language-server/lib/engine/index.js:181:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/dori/Projects/Work/project-v2/platform_v2/client/node_modules/apollo-language-server/lib/project/client.js:200:52
    at async OclifLoadingHandler.handle (/home/dori/Projects/Work/project-v2/platform_v2/client/node_modules/apollo/lib/OclifLoadingHandler.js:9:25)
    at async GraphQLClientProject.loadEngineData (/home/dori/Projects/Work/project-v2/platform_v2/client/node_modules/apollo-language-server/lib/project/client.js:198:9)
```

Here is the schema.graphql used by my apollo server:
```graphql
type User {
  id: ID!
  name: String
  avatar_url: String
  friends: [User] @relation(name: "FRIENDS", direction: "BOTH")
}

type Query {
  usersBySubstring(substring: String): [User]
    @cypher(
      statement: "MATCH (u:User) WHERE u.name CONTAINS $substring RETURN u"
    )
  currentUser: User @cypher(statement: """
    MATCH (u:User {id: $cypherParams.currentUserId})
    RETURN u
  """)
}

type Subscription {
  userOnline: User
}
```

related code in API server:
```ts
import { makeAugmentedSchema } from "neo4j-graphql-js";
import neo4j from "neo4j-driver";
import { typeDefs } from "./graphql-schema";

const schema = makeAugmentedSchema({
  typeDefs,
  //schemaDirectives: {
  //  isAuthenticated: IsAuthenticatedDirective,
  //  hasRole: HasRoleDirective,
  //  hasScope: HasScopeDirective,
  //},
});

const driver = neo4j.driver(
  process.env.NEO4J_URI || "bolt://localhost:7687",
  neo4j.auth.basic(
    process.env.NEO4J_USER || "neo4j",
    process.env.NEO4J_PASSWORD || "neo4j"
  )
);

const server = new ApolloServer({
  //mocks: true, // Dev only when not running neo4j
  context: ({ req }) => ({
    driver,
    cypherParams: {
      /* Inject the current user id in the context
      currentUserId: req.user ? req.user.id : null,
    },
  }),
  schema,
  introspection: true,
  playground: true,
  formatError: (err) => {
    console.log(err.stack);
    return err;
  },
```

apollo.config.js on server
```js
module.exports = {
  service: {
    localSchemaFile: "./src/schema.graphql",
  },
};
```

apollo.config.js on client
```js
module.exports = {
  client: {
    name: "Project [web]",
    service: {
      name: "project",
      localSchemaFile: "../api_server/src/schema.graphql",
    },
    excludes: ["**/__tests__/**/*"],
  },
};
```

**Comment by AdrienLemaire** [comment]
Following [this apollo-tooling comment](https://github.com/apollographql/apollo-tooling/issues/1484#issuecomment-562477636), I copied the following snippet found in [test/helpers/configTestHelpers.js](https://github.com/neo4j-graphql/neo4j-graphql-js/blob/b553b560737ad53ed57f816f10650a66d2f274f6/test/helpers/configTestHelpers.js#L23) into my schema.graphql file:
```graphql
directive @cypher(statement: String) on FIELD_DEFINITION
directive @relation(name: String, direction: _RelationDirections, from: String, to: String) on FIELD_DEFINITION | OBJECT
enum _RelationDirections {
  IN
  OUT
}
```

Now, I get types generated in `__generated__` directories

```console
$ npm run codegen

> project-client@2.0.1 codegen /home/dori/Projects/Work/project-v2/platform_v2/client
> apollo client:codegen --target typescript --watch

  ✔ Loading Apollo Project
  ✔ Generating query files with 'typescript' target - wrote 3 files
Press any key to stop.
[GraphQL error]: 406: Not Acceptable
Error: 406: Not Acceptable
    at ApolloEngineClient.loadSchemaTagsAndFieldStats (/home/dori/Projects/Work/project-v2/platform_v2/client/node_modules/apollo-language-server/lib/engine/index.js:181:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/dori/Projects/Work/project-v2/platform_v2/client/node_modules/apollo-language-server/lib/project/client.js:200:52
    at async OclifLoadingHandler.handle (/home/dori/Projects/Work/project-v2/platform_v2/client/node_modules/apollo/lib/OclifLoadingHandler.js:9:25)
    at async GraphQLClientProject.loadEngineData (/home/dori/Projects/Work/project-v2/platform_v2/client/node_modules/apollo-language-server/lib/project/client.js:198:9)
$ git status
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   ../api_server/src/schema.graphql

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        __generated__/
        src/__generated__/
        src/components/__generated__/
```

I don't understand what that last error is about though.

**Comment by xavier-taylor** [comment]
For anyone trying to autogenerate typescript types with neo4j-graphql, check out the library, check out https://graphql-code-generator.com rather than apollo codegen. I just followed the below guide and was able to generate types for my neo4j-graphql project.

https://www.ouestware.com/2020/09/08/GRAND-stack-one-schema-to-rule-them-all/

**Comment by michaeldgraham** [comment]
https://github.com/neo4j-graphql/neo4j-graphql-js/issues/608
