### ISSUE TITLE
Use @cypher to satisfy object type without returning an actual node

### ISSUE THREAD

**Issue by amoe** [neo4j-graphql/neo4j-graphql-js#510]
Really simple example:

```
type Person {
    name: String
}
type Query {
    persons: [Person] @cypher(statement: "WITH ['foo', 'bar'] AS x UNWIND x AS y RETURN y AS name")
}
```

I get the following error:

```
{
  "errors": [
    {
      "message": "String(\"foo\") (of class org.neo4j.values.storable.StringWrappingStringValue)",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "persons"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "code": "Neo.DatabaseError.General.UnknownError",
          "name": "Neo4jError",
          "stacktrace": [
            "Neo4jError: String(\"foo\") (of class org.neo4j.values.storable.StringWrappingStringValue)",
            "",
            "    at captureStacktrace (/home/amoe/dev/lysander-graphql-server/node_modules/neo4j-driver/lib/result.js:275:15)",
            "    at new Result (/home/amoe/dev/lysander-graphql-server/node_modules/neo4j-driver/lib/result.js:66:19)",
            "    at newCompletedResult (/home/amoe/dev/lysander-graphql-server/node_modules/neo4j-driver/lib/transaction.js:446:10)",
            "    at Object.run (/home/amoe/dev/lysander-graphql-server/node_modules/neo4j-driver/lib/transaction.js:285:14)",
            "    at Transaction.run (/home/amoe/dev/lysander-graphql-server/node_modules/neo4j-driver/lib/transaction.js:121:32)",
            "    at /home/amoe/dev/lysander-graphql-server/node_modules/neo4j-graphql-js/dist/index.js:190:25",
            "    at TransactionExecutor._safeExecuteTransactionWork (/home/amoe/dev/lysander-graphql-server/node_modules/neo4j-driver/lib/internal/transaction-executor.js:132:22)",
            "    at TransactionExecutor._executeTransactionInsidePromise (/home/amoe/dev/lysander-graphql-server/node_modules/neo4j-driver/lib/internal/transaction-executor.js:120:32)",
            "    at /home/amoe/dev/lysander-graphql-server/node_modules/neo4j-driver/lib/internal/transaction-executor.js:59:15",
            "    at new Promise (<anonymous>)"
          ]
        }
      }
    }
  ],
  "data": {
    "persons": null
  }
}
```

I think I understand what's happening here: `@cypher` expects a `Node` result value in order to resolve a specific object type in the schema.  Is this a hard limitation?  It seems like it should be possible to fulfil the object type using the results from the query without the data needing to be stored on a real node in the database.

**Comment by amoe** [comment]
You actually can do this very easily!  Just return a Cypher map.  `RETURN { name: y }` rather than `RETURN y AS name`.
