### ISSUE TITLE
Getting error when filtering null DateTime properties

### ISSUE THREAD

**Issue by CostaFernando** [neo4j-graphql/neo4j-graphql-js#547]
Hi guys,

In Neo4j and GraphQL schema I have nodes of type Task, that have the property "endDate", which are of type Neo4jDateTime. The property "endDate" can also be null.

In this context, I want to query all the not expired tasks, that means I want to get tasks that have "endDate" greater than a specified date or null. So I made this query:

```
query GetNotExpiredTasks($endDate: String){
  Task(filter:{OR: [{endDate_gte: {formatted: $endDate}}, {endDate: null}]}){
    taskId
    endDate{formatted}
  }
}
```

But I'm getting the following error:
```
{
  "errors": [
    {
      "message": "No such field: formatted",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "Task"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "code": "Neo.ClientError.Statement.ArgumentError",
          "name": "Neo4jError",
          "stacktrace": [
            "Neo4jError: No such field: formatted",
            ": ",
            "    at captureStacktrace (/app/node_modules/neo4j-driver/lib/result.js:277:15)",
            "    at new Result (/app/node_modules/neo4j-driver/lib/result.js:68:19)",
            "    at newCompletedResult (/app/node_modules/neo4j-driver/lib/transaction.js:449:10)",
            "    at Object.run (/app/node_modules/neo4j-driver/lib/transaction.js:287:14)",
            "    at Transaction.run (/app/node_modules/neo4j-driver/lib/transaction.js:123:32)",
            "    at _callee2$ (/app/node_modules/neo4j-graphql-js/dist/index.js:222:35)",
            "    at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:63:40)",
            "    at Generator.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:293:22)",
            "    at Generator.next (/app/node_modules/regenerator-runtime/runtime.js:118:21)",
            "    at asyncGeneratorStep (/app/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:5:24)"
          ]
        }
      }
    }
  ],
  "data": {
    "Task": null
  }
}
```

This is the Cypher generated by neo4j-graphql-js:
```
graphql-api             |   neo4j-graphql-js MATCH (`task`:`Task`) WHERE (ANY(_OR IN $filter.OR WHERE ((_OR.endDate_gte IS NULL OR `task`.endDate >= datetime(_OR.endDate_gte))) AND (_OR._endDate_null IS NULL OR _OR._endDate_null = TRUE AND NOT EXISTS(`task`.endDate)))) RETURN `task` { .taskId ,endDate: { formatted: toString(`task`.endDate) }} AS `task` +1m
graphql-api             |   neo4j-graphql-js {
graphql-api             |   "offset": 0,
graphql-api             |   "first": -1,
graphql-api             |   "filter": {
graphql-api             |     "OR": [
graphql-api             |       {
graphql-api             |         "endDate_gte": {
graphql-api             |           "formatted": "2020-01-01"
graphql-api             |         }
graphql-api             |       },
graphql-api             |       {
graphql-api             |         "_endDate_null": true
graphql-api             |       }
graphql-api             |     ]
graphql-api             |   },
graphql-api             |   "cypherParams": {}
graphql-api             | } +1ms
```

Do you know a best way for me to make this query? If I make the query separately, it works (in the images bellow).

![image](https://user-images.githubusercontent.com/17749414/100148728-e69f8080-2e7b-11eb-8f42-b61f40c47d20.png)
![image](https://user-images.githubusercontent.com/17749414/100148741-ea330780-2e7b-11eb-9649-cd38a2c90b99.png)
![image](https://user-images.githubusercontent.com/17749414/100148746-ed2df800-2e7b-11eb-9020-c6c809487d12.png)

**Comment by michaeldgraham** [comment]
https://github.com/neo4j-graphql/neo4j-graphql-js/issues/608
