### ISSUE TITLE
... On Not working

### ISSUE THREAD

**Issue by rsingh-27** [neo4j-graphql/neo4j-graphql-js#55]
I am using interfaces in my schema when I try to query with 

` ...on
syntax I get the following error

```
TypeError: Cannot read property 'value' of undefined
    at buildCypherSelection (/app/node_modules/neo4j-graphql-js/dist/selections.js:43:38)
    at buildCypherSelection (/app/node_modules/neo4j-graphql-js/dist/selections.js:77:12)
    at cypherQuery (/app/node_modules/neo4j-graphql-js/dist/index.js:137:76)
    at _callee$ (/app/node_modules/neo4j-graphql-js/dist/index.js:41:23)
    at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/app/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /app/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (/app/node_modules/core-js/library/modules/es6.promise.js:177:7)

```

**Comment by eljenso** [comment]
Any news on this? Getting the same error.

**Comment by johnymontana** [comment]
@eljenso Yes, this is a glaring omission. We will bump the priority up on this to get it fixed soon.

**Comment by johnymontana** [comment]
We've added initial support for Inline Fragments in v1.0.1. Please test and let us know how it works. See #103 for more info.

**Comment by johnymontana** [comment]
Closing this as a duplicate of #103, as there's a bit more discussion there. Please track in #103.
