### ISSUE TITLE
Version problem

### ISSUE THREAD

**Issue by nicolair** [neo4j-graphql/neo4j-graphql-js#573]
hello,
I have an apollo server wich run well with the 2.18 version of neo4j-graphql-js module but not with the 2.19 version. With

    `node maquisdoc-apollo.js `

I get the following report:

    [remy@Remy-003 maquisdoc-graphql]$ node maquisdoc-apollo.js 
    /home/remy/Documents/maquisdoc_code/maquisdoc-graphql/node_modules/@graphql-tools/utils/index.cjs.js:240
            throw new graphql.GraphQLError(`Argument "${name}" has invalid value ${graphql.print(valueNode)}.`, valueNode);
            ^

    GraphQLError [Object]: Argument "direction" has invalid value "OUT".
    at getArgumentValues (/home/remy/Documents/maquisdoc_code/maquisdoc-graphql/node_modules/@graphql-   tools/utils/index.cjs.js:240:19)
    at /home/remy/Documents/maquisdoc_code/maquisdoc-graphql/node_modules/@graphql-tools/utils/index.cjs.js:3074:32
    at Array.forEach (<anonymous>)
    at visitorSelector (/home/remy/Documents/maquisdoc_code/maquisdoc-graphql/node_modules/@graphql-tools/utils/index.cjs.js:3066:32)
    at callMethod (/home/remy/Documents/maquisdoc_code/maquisdoc-graphql/node_modules/@graphql-tools/utils/index.cjs.js:2726:24)
    at visitFields (/home/remy/Documents/maquisdoc_code/maquisdoc-graphql/node_modules/@graphql-tools/utils/index.cjs.js:2868:30)
    at visit (/home/remy/Documents/maquisdoc_code/maquisdoc-graphql/node_modules/@graphql-tools/utils/index.cjs.js:2796:17)
    at /home/remy/Documents/maquisdoc_code/maquisdoc-graphql/node_modules/@graphql-tools/utils/index.cjs.js:2784:41
    at Array.forEach (<anonymous>)
    at visit (/home/remy/Documents/maquisdoc_code/maquisdoc-graphql/node_modules/@graphql-tools/utils /index.cjs.js:2777:37) {  
      locations: [ { line: 172, column: 141 } ]
    }

   
I am using a fedora 33 machine. My `maquisdoc-apollo.js` file follows

    const { makeAugmentedSchema } = require("neo4j-graphql-js")
    const {ApolloServer} = require("apollo-server")
    const neo4j = require("neo4j-driver")
    
    const typeDefs = /* GraphQL */ `
      type .....
    `
    const schema = makeAugmentedSchema({typeDefs})
    
    const neo4j_url = "bolt://localhost:7687"
    const neo4j_pw = process.env.NEO4J_PASSWORD
    const neo4j_username = process.env.NEO4J_USERNAME
    
    const driver = neo4j.driver(
      neo4j_url,
      neo4j.auth.basic(neo4j_username,neo4j_pw)
    );
    
    const server = new ApolloServer({schema, context: {driver}})
    
    server.listen(3003,"0.0.0.0")
      .then(({ url }) => {
      console.log(`GraphQL ready at ${url}`);
    });

**Comment by dmoree** [comment]
Sorry this so late, but the problem lies in `@relation(name: "...", direction: "OUT")` as referenced in the error thrown. The solution is simply to remove the double quotes from every `direction` argument of the `@relation` directive. The value for the `direction` argument has become an `enum` since `2.19.0`.

`@relation(name: "...", direction: "OUT")`
becomes
`@relation(name: "...", direction: OUT)`

Solution is referenced [here](https://github.com/neo4j-graphql/neo4j-graphql-js/issues/565#issuecomment-756189910)

**Comment by nicolair** [comment]
Thank you. Ok now
