### ISSUE TITLE
Duplicated generated mutation names

### ISSUE THREAD

**Issue by johnymontana** [neo4j-graphql/neo4j-graphql-js#92]
Currently, the names for relationship mutation operations are based only on node labels (for example `AddPersonMovie`) and not relationship type, which results in duplicate mutation names.

```
type Person {
  id: ID!
  name: String
  moviesActedIn: [Movie] @relation(name: "ACTED_IN", direction: "OUT")
  moviesProduced: [Movie] @relation(name: "PRODUCED", direction: "OUT")
}


type Movie {
  id: ID!
  title: String
  actors(first: Int = 10, offset: Int = 0): [Person] @relation(name: "ACTED_IN", direction: "IN")
  producers(first: Int = 10, offset: Int = 0): [Person] @relation(name: "PRODUCED", direction: "IN")
  writers(first: Int = 10, offset: Int = 0): [Person] @relation(name: "WROTE", direction: "IN")
  reviewers(first: Int = 10, offset: Int = 0): [Person] @relation(name: "REVIEWED", direction: "IN")
}

enum _UserOrdering {
  name_asc
  name_desc
}

type Query {
    people(id: ID, name: String, first: Int = 10, offset: Int = 0, orderBy: _UserOrdering): [Person]
    movies(id: ID, name: String, first: Int = 10, offset: Int = 0): [Movie]
}
```

```
{
  "error": {
    "errors": [
      {
        "message": "Field Mutation.AddPersonMovie can only be defined once.\n\nField Mutation.RemovePersonMovie can only be defined once.",
        "extensions": {
          "code": "GRAPHQL_VALIDATION_FAILED",
          "exception": {
            "stacktrace": [
              "Error: Field Mutation.AddPersonMovie can only be defined once.",
              "",
              "Field Mutation.RemovePersonMovie can only be defined once.",
              "    at assertValidSchema (/Users/markneedham/projects/grand-stack-starter/api/node_modules/graphql/type/validate.js:82:11)",
              "    at Object.validate (/Users/markneedham/projects/grand-stack-starter/api/node_modules/graphql/validation/validate.js:58:35)",
              "    at Promise.resolve.then (/Users/markneedham/projects/grand-stack-starter/api/node_modules/apollo-server-express/node_modules/apollo-server-core/src/runQuery.ts:188:30)",
              "    at process._tickCallback (internal/process/next_tick.js:68:7)"
            ]
          }
        }
      }
    ]
  }
}
```

**Comment by johnymontana** [comment]
This was fixed in #94, including the field name in the name of the generated mutations. The arguments for mutations also now use type inputs.
